### ISSUE TITLE
Compare collections

### ISSUE THREAD

**Issue by jwovens** [jwovens/plTAP#2]
Need low level function in the library to compare 2 in-memory collections e.g. nested table is good start.

This will enable queries, cursors, tables to be compared as well as in-memory collections.

Current problem is that nested tables may be compared natively within Oracle, providing the table is of a scalar type.  There's not any easy way to natively compare nested table of a `%ROWTYPE`

**Comment by armeniopinto** [comment]
I was dozing on the sofa and you just woke me up, thanks for that!

AP
